services:
  ttskch_paginator.config:
    public: true
    class: Ttskch\PaginatorBundle\Config
    properties:
      pageName: '%ttskch_paginator.page.name%'
      pageRange: '%ttskch_paginator.page.range%'
      limitName: '%ttskch_paginator.limit.name%'
      limitDefault: '%ttskch_paginator.limit.default%'
      sortKeyName: '%ttskch_paginator.sort.key.name%'
      sortDirectionName: '%ttskch_paginator.sort.direction.name%'
      sortDirectionDefault: '%ttskch_paginator.sort.direction.default%'
      templatePager: '%ttskch_paginator.template.pager%'
      templateSortable: '%ttskch_paginator.template.sortable%'

  ttskch_paginator.context:
    public: true
    class: Ttskch\PaginatorBundle\Context
    arguments:
      - '@ttskch_paginator.config'
      - '@request_stack'
      - '@form.factory'

  Ttskch\PaginatorBundle\Twig\TtskchPaginatorExtension:
    tags: { name: twig.extension }
    arguments:
      - '@ttskch_paginator.context'
      - '@twig'

  # alias for autowiring
  Ttskch\PaginatorBundle\Context: '@ttskch_paginator.context'
